### ISSUE TITLE
Emoji Icon resource/list

### ISSUE THREAD

**Issue by Falieson** [ngryman/cz-emoji#10]
I basically want to have the same types as provided by the default `cz-conventional-log` package. I figure others maybe doing the same so I'll update this with a link to the commit when I'm done.

Meanwhile, this is the emoji list I'm using: https://gist.github.com/rxaviers/7360908 is there a better one? Is there anything inaccurate about using this? ... I guess I'm not sure what "beetle" (the value) should correspond too.

**Update:** my commit and list of types: https://github.com/Falieson/typescript-react-asteroid-meteor/commit/8115b067d40694f03b9eee3854495ea37fa5c3d4#diff-13e9c5d8bf5e473ad89e449a16c9ef5fR6

Enjoy and Thanks!

**Comment by ngryman** [comment]
Hey sorry I'm late again.

Your link seems broken, linking to your types for posterity: https://github.com/Falieson/TRAM/blob/master/package.json#L17.

Perhaps we could add a section in the docs with some predefined types?

**Comment by Falieson** [comment]
I think that'd be a great idea! Here's my latest...
```
  "config": {
    "cz-emoji": {
      "types": [
        {
          "name": "feat \t\t🌟  A new feature",
          "value": ":star2:"
        },
        {
          "name": "fix \t\t🐞  A bug fix",
          "value": ":beetle:"
        },
        {
          "name": "test \t\t🚓  Testing improved with new or fixed tests",
          "value": ":police_car:"
        },
        {
          "name": "chore \t🔩  Doesn't modify src or test files",
          "value": ":nut_and_bolt:"
        },
        {
          "name": "style \t✏️  Doesn't affect the meaning of the code (white-space, semi-colons, etc)",
          "value": ":pencil2:"
        },
        {
          "name": "docs \t\t📚  Documentation change",
          "value": ":books:"
        },
        {
          "name": "refactor \t🎨  Neither fixes a bug nor adds a feature",
          "value": ":art:"
        },
        {
          "name": "perf \t\t💰  Improves performance with this change",
          "value": ":moneybag:"
        },
        {
          "name": "build \t🚀  Build system config or external dependencies",
          "value": ":rocket:"
        },
        {
          "name": "ci \t\t🚥  CI config files and scripts",
          "value": ":traffic_light:"
        },
        {
          "name": "revert \t💊  Reverts a previous commit",
          "value": ":pill:"
        },
        {
          "name": "upgrade \t⤴️  Upgrades a repo package or a starter-kit from an upstream",
          "value": ":arrow_heading_up:"
        }
      ],
      "scopes": [
        "$config",
        "$data",
        "$dev",
        "$pkg",
        "$struct",
        "$stack",
        "$ui"
      ]
    },
    "commitizen": {
      "path": "./node_modules/cz-emoji"
    }
  },```

**Comment by Falieson** [comment]
And I use this list of emojis: https://github.com/scotch-io/All-Github-Emoji-Icons

**Comment by ngryman** [comment]
Hey @Falieson,

Happy that you like the new defaults!

The API has also probably changed since your last comment: https://github.com/ngryman/cz-emoji#types. Do you think it could be related to your error?
