### ISSUE TITLE
Use Gitmoji for reference

### ISSUE THREAD

**Issue by wldcordeiro** [ngryman/cz-emoji#11]
https://gitmoji.carloscuesta.me/ has a list of common emoji in commit messages. It'd be nice to have these all available.

**Comment by ngryman** [comment]
I didn't knew about it, so cool. I could add predefined configs, including that one.

**Comment by ngryman** [comment]
@wldcordeiro It's available by default now :)

**Comment by wldcordeiro** [comment]
@ngryman Doh! I hadn't looked at what you did and made my own today https://github.com/wldcordeiro/cz-gitmoji-changelog
