### ISSUE TITLE
Allow per project .czrc customizations to cz-emoji

### ISSUE THREAD

**Issue by devkabiir** [ngryman/cz-emoji#20]
Currently the script checks for `package.json` for `config['cz-emoji']` object and if it doesn't find it, it defaults to the global `.czrc` (in home directory) but it is possible to have a project level `.czrc`. And commitizen supports that. I'm using cz-emoji outside of js projects too and they don't always have `package.json`

**Comment by kstolte** [comment]
I also am running into this. I'll work on a fix and submit a pull it if no one else has started.

**Comment by ngryman** [comment]
@kstolte That would be awesome, thanks!

**Comment by kstolte** [comment]
@ngryman, No problem. I did some work on it this past weekend. If for some reason there is a `package.json` and a `.czrc` in the directory, we should go with the settings in the `.czrc` correct?

**Comment by ngryman** [comment]
@kstolte I think it might be worth to try [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) for that.

**Comment by kstolte** [comment]
Oh that is cool. I'll definitely check that out.

**Comment by ngryman** [comment]
Hey guys, I just made a quick pass of improvements and ended up implementing that feature. Would you mind giving the pre-release a try? To do you can specify `next` as the version. Thanks!

**Comment by RikardGehlin** [comment]
Works for me! 👍

**Comment by ngryman** [comment]
Thanks, closing the issue then.
