### ISSUE TITLE
Global commitizen doesn't work

### ISSUE THREAD

**Issue by patarapolw** [ngryman/cz-emoji#40]
Did you forget to push new version of `cz-emoji` to NPM?

The error is exactly here, I think.

https://github.com/ngryman/cz-emoji/blob/0be8cc5109ba7466b0d3cf7174f3c1370525aa58/index.js#L45

`res.path` will be `undefined` if there is no local `.czrc`.

**Comment by AkatQuas** [comment]
same problem here

**Comment by joshikeno** [comment]
QuickFix: https://github.com/ngryman/cz-emoji/blob/master/index.js#L46

**Comment by ngryman** [comment]
Version [1.2.2](https://github.com/ngryman/cz-emoji/releases/tag/v1.2.2) has been pushed recently and should fix this issue. Sorry for the late notice.
