### ISSUE TITLE
[feature request]: Making cz-emoji commits semantic compliant

### ISSUE THREAD

**Issue by Clumsy-Coder** [ngryman/cz-emoji#43]
It'd be nice to have the git commit messages to be semantic compliant.

What I mean is that it follows the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) rules
Compatible with [semantic pull requests](https://github.com/zeke/semantic-pull-requests)
And works with [semantic-release](https://github.com/semantic-release/semantic-release) (for creating changelogs)

Of course adding the emoji is also nice, as mentioned in https://github.com/ngryman/cz-emoji/pull/32
But the owner of the pull request hasn't responded for a while. And I've been waiting for the pull request to be merged.

**Comment by ngryman** [comment]
@Clumsy-Coder Could you give me an example to illustrate what a semantic compliant message could look like with `cz-emoji`?

**Comment by Clumsy-Coder** [comment]
something like

`dep-add(npm): :heavy_plus_sign: add cz-emoji npm package`

dep-add(npm): ➕ add cz-emoji npm package

kinda like issue https://github.com/ngryman/cz-emoji/issues/31

**Comment by ngryman** [comment]
@Clumsy-Coder Gotcha thanks.

It makes sense to me and doesn't involve so many changes.
I've added a new `conventional` option to the configuration. If set to `true`, it will format the message as you suggested.

Could you install the bleeding edge `cz-emoji` on `master`?

```diff
-  "cz-emoji": "^1.2.2"
+  "cz-emoji": "ngryman/cz-emoji"
```

Let me know if it works for you. If so I'll release a new version.

**Comment by Clumsy-Coder** [comment]
Just need to add docs to README on how to use conventional commits. Other than that, it looks good to me. 

NOTE: it needs a `BREAKING CHANGE` section. I already have it implemented. I'll create a pull request for it.

**Comment by ngryman** [comment]
Following-up in #44.

**Comment by Jack-Barry** [comment]
I had some trouble getting this working in conjunction with `commitlint`, but adding this to my `commitlint.config.js` seemed to do the trick:

```js
const commitTypes = require('cz-emoji/lib/types.json')

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [2, 'always', commitTypes.map((type) => type.name)],
  },
}
```

Just want to make sure I'm not doing something stupid here? If it *is* stupid - please let me know

If it's not stupid I'd be happy to add this to the docs for `cz-emoji`
