### ISSUE TITLE
.czrc is not used at root directory if package.json does not exist

### ISSUE THREAD

**Issue by B-Galati** [ngryman/cz-emoji#47]
Hello,

I noticed that if there is not `package.json` file at root directory then the `.czrc` file is not used.

It looks to be something supported by `cz-cli` though.

Let me know how I could help.
Cheers.

**Comment by ngryman** [comment]
Hey @B-Galati, by the root directory, do you mean the root directory of your project?

**Comment by B-Galati** [comment]
> Hey @B-Galati, by the root directory, do you mean the root directory of your project?

Yes!

**Comment by ngryman** [comment]
Gotcha! This is pretty standard behavior in the JavaScript ecosystem as projects always have a `package.json`.

If for some reason you're using `cz-emoji` in a different context, I would suggest putting your `.czrc` file in your home directory [as suggested by commitizen](https://github.com/commitizen/cz-cli#conventional-commit-messages-as-a-global-utility).

Let me know if this works for you.

**Comment by B-Galati** [comment]
No, it does not :grin:

We are using this tool for a backend project without Javascript.

And we have a different `.czrc` for each project so it would not fit our need to use the home directory.

Contrary to `cz-emoji`, `commitizen` works as expected without any `package.json` at project root directory.

They are using something more generic to achieve that goal: https://github.com/commitizen/cz-cli/blob/a6adb3b1f7cc19c5a8f011d2c189de0dc03bfceb/src/configLoader/findup.js#L8

**Comment by ngryman** [comment]
Yea that makes sense. It's pretty easy to support upward searching, so I don't see no reason to not do it. I've opened a PR here: #48
