### ISSUE TITLE
Example Repos

### ISSUE THREAD

**Issue by joefraley** [ngryman/cz-emoji#5]
A list of example repos using this commit convention in the readme would be helpful. It's hard to figure out how best to integrate this into a release cycle.

**Comment by ngryman** [comment]
Sure, what about a link in the `readme` to propose anyone using `cz-emoji` to add a repo to the list?

**Comment by Falieson** [comment]
https://github.com/Falieson/typescript-react-asteroid-meteor/commit/8115b067d40694f03b9eee3854495ea37fa5c3d4#diff-13e9c5d8bf5e473ad89e449a16c9ef5fR6

**Comment by ngryman** [comment]
A little late sorry, I added a section for that.

**Comment by Falieson** [comment]
Link was broken, updated with: https://github.com/Falieson/TRAM/commit/9f3c380585f3e58756e84c7af59f73d6bc469813#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
