### ISSUE TITLE
Custom breaking question not working

### ISSUE THREAD

**Issue by MauricioTD** [ngryman/cz-emoji#69]
I'm trying to add a custom question to the "BREAKING" part of the commit wizard but its not getting the change

config: 
```javascript

"cz-emoji": {
      "conventional": true,
      "questions":{
        "type" : "Selecciona el tipo del commit:",
        "scope" : "¿Cuál es el scope (archivo, tag o nombre)? (opcional):",
        "subject": "Título descriptivo corto:",
        "body" : "Descripción detallada del cambio (opcional):",
        "breaking": "¿Estos cambios rompen alguna parte del sistema? (opcional):",
        "issues": "Issues relacionados (ej:#1, #2, ...) (opcional):"
      },
}
```
![image (1)](https://user-images.githubusercontent.com/97047898/150879955-145d7bd4-034b-4bd7-b8fd-d8da301493ad.png)

Am I doing something wrong?

**Comment by JhonGdl** [comment]
I'm trying the same thing, and I haven't succeeded yet

**Comment by ngryman** [comment]
A bit late, sorry about that. It should be fixed in the upcoming release. Meanwhile, you can install the canary version with: `npm install -g cz-emoj@canary`.
