### ISSUE TITLE
using options in .czrc ?

### ISSUE THREAD

**Issue by oneezy** [ngryman/cz-emoji#70]
Is it possible to use the options in the `.czrc` file instead of `package.json` ?

i.e. i'm trying to do something like this

**.czrc**
```json
{
  "path": "./node_modules/cz-emoji",
  "cz-emoji": {
    "skipQuestions": ["scope", "issues"]
  }
}
```

**Comment by AndreAugustoAAQ** [comment]
> Is it possible to use the options in the `.czrc` file instead of `package.json` ?

Yes it's possible

> 
> i.e. i'm trying to do something like this
> 
> **.czrc**
> 
> ```json
> {
>   "path": "./node_modules/cz-emoji",
>   "cz-emoji": {
>     "skipQuestions": ["scope", "issues"]
>   }
> }
> ```
An key is missing, if you can't use it, that's probably the reason

As you can see in how-to section, a key `config` is needed before key `cz-emoji`
[ngryman/cz-emoji#how-to](https://github.com/ngryman/cz-emoji#how-to)

Your example looks like this:
```json
{
  "path": "./node_modules/cz-emoji",
  "config": {
    "cz-emoji": {
      "skipQuestions": ["scope", "issues"]
    }
  }
}
```
