### ISSUE TITLE
looks like project is dead

### ISSUE THREAD

**Issue by victorsoares96** [ngryman/cz-emoji#74]
i've been following issues and pull request and looks like the project is no longer maintained, someone else know of some project similar and alive?

**Comment by ngryman** [comment]
It's still alive... buuut has been hibernating, let's say 😄

I confess it's not on my top priority list, so I didn't give it lots of attention in the past year. That being said, I just merged PRs and pushed a couple of fixes which, hopefully, should close all pending issues.

You can try the next release by installing the canary version with `npm i -g cz-emoji@canary`. I'll wait for feedback from other issues and eventually publish it.

Closing the issue as I answered your initial question.
