### ISSUE TITLE
Symbol feature appears to be broken

### ISSUE THREAD

**Issue by no2chem** [ngryman/cz-emoji#76]
When I use the symbol feature, it appears that I get an error:

```
Cannot read properties of undefined (reading 'name')
Aborting commit due to empty commit message.
```

Haven't had a chance to look into it, but seems related to how search is performed in the json file.

**Comment by ngryman** [comment]
Hi @no2chem, I recently published a new canary version. Could you check that your bug is still happening? You can install it with: `npm install cz-emoji@canary`.

**Comment by no2chem** [comment]
Yeah, I'm on 1.3.2-canary.2 and still see it happening.

**Comment by adrien-zenchef** [comment]
Hi, any news about this error ?

**Comment by simrobin** [comment]
Hey @ngryman 👋 !
I think I have got a fix for this on the above PR ⬆️. 
Let me know if you need some context or how I can help for the review.

**Comment by ndousson** [comment]
Hi @ngryman 👋 
Can you check the PR opened by @simrobin ?
The issue always happen with the canary release and we need to use an older version (1.3.1).
Thanks 🙏 and have a nice day 🌞

**Comment by ngryman** [comment]
Sorry for the super late answer... I just merged the PR. I'll publish the package in a couple days (some issues with the npm repo). Let me know if that version works for you so I can release `1.3.2`. Thanks!

**Comment by ndousson** [comment]
Thanks and no worry 😉 

How can I test that's working without having package available on the NPM registry ?

**Comment by simrobin** [comment]
@ngryman Thanks for reviewing and merging, that version works for me: 
```
> g cz
cz-cli@4.3.0, cz-emoji@1.3.2-canary.3

? Select the type of change you're committing: chore      🛠️  Refactoring or any technical task.
? Specify a Linear ID: {teamId}-{issueId} test
? Write a short description: testing commitlint
? Provide a longer description:
? A BREAKING CHANGE commit requires a body. Please enter a longer description of the commit itself:

[test 7b7bd1547f] 🛠️ (test) testing commitlint
 1 file changed, 1 insertion(+)
 create mode 100644 test
```

@ndousson You can install it this way `npm install -g cz-emoji@1.3.2-canary.3`
