### ISSUE TITLE
Parenthesis not inserted in scope

### ISSUE THREAD

**Issue by israelroldan** [ngryman/cz-emoji#8]
I'm loving the concept of this adapter, but there's an issue with scopes, parenthesis are not inserted, I'm getting commit messages like these:

    {emoji} {scope}{commit message}

instead of

    {emoji} ({scope}) {commit message}

**Comment by israelroldan** [comment]
It seems this has been fixed with https://github.com/ngryman/cz-emoji/pull/2, do you think you could publish a new release?

**Comment by ngryman** [comment]
Yes sorry about that, [0.2.0](https://github.com/ngryman/cz-emoji/releases/tag/v0.2.0) published.
